Clothes = Clothes or class({})

function Clothes:GetItemTypes(item)
    local types = {}

    for type, tbl in pairs(Clothes.items) do
        for _, v in pairs(tbl) do
            if not types[v] then
                types[v] = {}
            end
            types[v][type] = true
        end
    end

    return types[item]
end


Clothes.items = {
    -- Any item considered boots for stoneskin gland
    ["boots"] = {
        "item_slippers",
        "item_boots",
        "item_travel_boots",
        "item_travel_boots_2",
        "item_phase_boots",
        "item_arcane_boots",
        "item_tranquil_boots",
        "item_guardian_greaves",
        "item_spider_legs",
        "item_force_boots",
    },
    -- Any item considered to require hands for power claws
    ["hands"] = {
        "item_gauntlets",
        "item_ogre_axe",
        "item_blade_of_alacrity",
        "item_staff_of_wizardry",
        "item_quelling_blade",
        "item_blades_of_attack",
        "item_gloves",
        "item_quarterstaff",
        "item_broadsword",
        "item_blitz_knuckles",
        "item_javelin",
        "item_claymore",
        "item_mithril_hammer",
        "item_magic_stick",
        "item_ghost",
        "item_blink",
        "item_magic_wand",
        "item_falcon_blade",
        "item_oblivion_staff",
        "item_hand_of_midas",
        "item_force_staff",
        "item_witch_blade",
        "item_cyclone",
        "item_rod_of_atos",
        "item_dagon",
        "item_dagon_2",
        "item_dagon_3",
        "item_dagon_4",
        "item_dagon_5",
        "item_orchid",
        "item_ultimate_scepter",
        "item_sheepstick",
        "item_gungir",
        "item_wind_waker",
        "item_black_king_bar",
        "item_hurricane_pike",
        "item_manta",
        "item_lesser_crit",
        "item_meteor_hammer",
        "item_basher",
        "item_invis_sword",
        "item_desolator",
        "item_bfury",
        "item_ethereal_blade",
        "item_nullifier",
        "item_monkey_king_bar",
        "item_butterfly",
        "item_radiance",
        "item_greater_crit",
        "item_silver_edge",
        "item_rapier",
        "item_bloodthorn",
        "item_abyssal_blade",
        "item_dragon_lance",
        "item_sange",
        "item_yasha",
        "item_kaya",
        "item_echo_sabre",
        "item_maelstrom",
        "item_diffusal_blade",
        "item_mage_slayer",
        "item_heavens_halberd",
        "item_kaya_and_sange",
        "item_sange_and_yasha",
        "item_yasha_and_kaya",
        "item_mjollnir",
        "item_overwhelming_blink",
        "item_swift_blink",
        "item_arcane_blink",
        "item_demon_edge",
        "item_mystic_staff",
        "item_reaver",
        "item_relic",
        "item_broom_handle",
        "item_trusty_shovel",
        "item_unstable_wand",
        "item_pogo_stick",
        "item_misericorde",
        "item_grove_bow",
        "item_paladin_sword",
        "item_mind_breaker",
        "item_ninja_gear",
        "item_the_leveller",
        "item_penta_edged_sword",
        "item_desolator_2",
        "item_fallen_sky",
    },
    -- Any item considered a head item for eye of apollo
    ["head"] = {
        "item_mantle",
        "item_circlet",
        "item_crown",
        "item_helm_of_iron_will",
        "item_sobi_mask",
        "item_fluffy_hat",
        "item_cloak",
        "item_lifesteal",
        "item_voodoo_mask",
        "item_wraith_band",
        "item_mask_of_madness",
        "item_helm_of_the_dominator",
        "item_helm_of_the_overlord",
        "item_headdress",
        "item_vladmir",
        "item_veil_of_discord",
        "item_hood_of_defiance",
        "item_eternal_shroud",
        "item_satanic",
        "item_skadi",
        "item_possessed_mask",
        "item_cloak_of_flames",
        "item_psychic_headband",
        "item_ascetic_cap",
        "item_trickster_cloak",
        "item_pirate_hat",
    },
    -- Any item considered clothing for the nudist trait
    ["clothes"] = {
        "item_gauntlets",
        "item_slippers",
        "item_mantle",
        "item_belt_of_strength",
        "item_boots_of_elves",
        "item_robe",
        "item_gloves",
        "item_chainmail",
        "item_helm_of_iron_will",
        "item_sobi_mask",
        "item_fluffy_hat",
        "item_cloak",
        "item_boots",
        "item_lifesteal",
        "item_voodoo_mask",
        "item_wraith_band",
        "item_bracer",
        "item_power_treads",
        "item_phase_boots",
        "item_mask_of_madness",
        "item_hand_of_midas",
        "item_helm_of_the_dominator",
        "item_travel_boots",
        "item_helm_of_the_overlord",
        "item_headdress",
        "item_tranquil_boots",
        "item_arcane_boots",
        "item_vladmir",
        "item_guardian_greaves",
        "item_veil_of_discord",
        "item_glimmer_cape",
        "item_hood_of_defiance",
        "item_blade_mail",
        "item_eternal_shroud",
        "item_crimson_guard",
        "item_shivas_guard",
        "item_assault",
        "item_basher",
        "item_satanic",
        "item_chipped_vest",
        "item_possessed_mask",
        "item_nether_shawl",
        "item_vambrace",
        "item_elven_tunic",
        "item_cloak_of_flames",
        "item_ceremonial_robe",
        "item_ascetic_cap",
        "item_trickster_cloak",
        "item_force_boots",
        "item_pirate_hat",
    },
}
